application: skraflhjalp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /apple-touch-icon.png
  static_files: static/touch-icon-ipad-retina.png
  upload: static/touch-icon-ipad-retina.png
- url: /touch-icon-ipad.png
  static_files: static/touch-icon-ipad.png
  upload: static/touch-icon-ipad.png
- url: /touch-icon-ipad-retina.png
  static_files: static/touch-icon-ipad-retina.png
  upload: static/touch-icon-ipad-retina.png
- url: /touch-icon-iphone-retina.png
  static_files: static/touch-icon-iphone-retina.png
  upload: static/touch-icon-iphone-retina.png
- url: .*
  script: skrafl.app

skip_files:
- ^(.*/)?.*\.txt$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
